import { MetadataRoute } from 'next';

const BASE = 'https://spraybosspro.com';

const hubPages = [
  '/lawn-care-scheduling-software',
  '/fertilizer-software',
  '/weed-control-software',
  '/pest-control-scheduling-software',
  '/mosquito-control-software',
  '/spray-business-software',
  '/pest-control-software',
  '/lawn-care-software',
  '/mosquito-spray-software',
];

const vsPages = [
  '/vs-aspire',
  '/vs-clip',
  '/vs-fieldroutes',
  '/vs-gorilladesk',
  '/vs-housecallpro',
  '/vs-jobber',
  '/vs-lawnpro',
  '/vs-realgreen',
  '/vs-serviceautopilot',
  '/vs-servicetitan',
  '/vs-spraye',
];

const blogSlugs = [
  // Lawn Care Scheduling
  'how-to-build-lawn-care-routes-fast',
  'lawn-care-scheduling-mistakes',
  'schedule-recurring-lawn-treatments-automatically',
  'lawn-care-route-optimization',
  'manage-multiple-lawn-care-crews',
  'lawn-care-waiting-list',
  'track-square-footage-lawn-care',
  'dispatch-lawn-care-technicians',
  'lawn-care-scheduling-software-vs-field-service-software',
  'scale-lawn-care-business-without-office-manager',
  'automate-lawn-care-customer-reminders',
  'lawn-care-software-vs-spreadsheets',
  'handle-overdue-lawn-care-treatments',
  'what-lawn-care-customers-expect',
  'weekly-lawn-care-schedule',
  'price-lawn-care-services-by-square-footage',
  'seasonal-lawn-care-scheduling',
  'map-based-routing-lawn-care',
  'track-lawn-care-service-history',
  'what-to-look-for-lawn-care-scheduling-software',
  // Fertilizer
  'track-5-round-6-round-fertilizer-programs',
  'epa-registration-numbers-fertilizer-applications',
  'auto-schedule-fertilizer-rounds',
  'fertilizer-application-rates-compliance-logging',
  'build-fertilizer-route-map-based-routing',
  'lawn-care-compliance-records-fertilizer',
  'manage-fertilizer-program-round-1-to-winterizer',
  'granular-vs-liquid-fertilizer-application-tracking',
  'train-technicians-log-fertilizer-applications',
  'state-inspector-fertilizer-application-records',
  'schedule-fall-fertilizer-winterizer-rounds',
  're-entry-interval-texts-fertilizer-application',
  'fertilizer-software-vs-lawn-care-scheduling-tools',
  'manage-commercial-fertilizer-accounts',
  'know-when-customer-due-fertilizer-round',
  'fertilizer-program-pricing-square-foot',
  'fertilizer-compliance-logs-vs-spreadsheets',
  'handle-overdue-fertilizer-rounds',
  'fertilizer-round-waiting-list',
  'scale-fertilizer-program-business',
  // Weed Control
  'pre-emergent-vs-post-emergent-weed-control-scheduling',
  'when-to-apply-pre-emergent-weed-control',
  'auto-schedule-post-emergent-weed-control',
  're-entry-interval-weed-control-applications',
  'log-epa-reg-numbers-weed-control',
  'track-pre-emergent-post-emergent-programs-separately',
  'build-weed-control-routes-circle-map',
  'compliance-records-weed-control-applications',
  'manage-broadleaf-weed-control-fertilizer-programs',
  'automatic-re-entry-interval-texts-weed-control',
  'nutsedge-specialty-weed-control-programs',
  'fall-pre-emergent-scheduling',
  'know-which-customers-due-weed-control',
  'weed-control-pricing-square-foot',
  'train-technicians-log-weed-control-applications',
  'weed-control-scheduling-mistakes',
  'weed-control-software-vs-generic-scheduling-tools',
  'manage-weed-control-fertilizer-same-customers',
  'what-customers-expect-after-weed-control',
  'scale-weed-control-program',
  // Pest Control Scheduling
  'manage-quarterly-bi-monthly-monthly-pest-control-programs',
  'auto-scheduling-pest-control-visits',
  'build-pest-control-routes-circle-map',
  'epa-compliance-records-pest-control',
  're-entry-interval-texts-pest-control',
  'dispatch-pest-control-technicians',
  'quarterly-vs-bi-monthly-pest-control-programs',
  'handle-overdue-pest-control-treatments',
  'pest-control-route-revenue-waiting-list',
  'log-target-pest-treatment-areas-epa-reg-numbers',
  'mosquito-add-on-pest-control-customers',
  'scale-pest-control-business-recurring-customers',
  'what-pest-control-customers-expect',
  'train-pest-control-technicians-application-logs',
  'pest-control-software-vs-field-service-software',
  'interior-exterior-pest-control-treatment-logs',
  'monthly-pest-control-programs-predictable-revenue',
  'reduce-pest-control-cancellations-sms-alerts',
  'know-which-pest-control-customers-due',
  'pest-control-software-recurring-programs',
  // Mosquito Control
  'schedule-mosquito-control-treatments-seasonal-intervals',
  'build-mosquito-control-routes-circle-map',
  're-entry-interval-mosquito-barrier-spray',
  'auto-schedule-mosquito-treatments',
  'log-mosquito-control-applications-epa-compliance',
  'add-mosquito-control-programs-lawn-care-pest-control',
  'automated-sms-alerts-mosquito-control',
  'manage-mosquito-control-season',
  'price-mosquito-control-services',
  'mosquito-control-waiting-list',
  'train-technicians-mosquito-control-application-logs',
  'manage-mosquito-control-lawn-care-customers',
  'what-customers-want-after-mosquito-barrier-spray',
  'scale-mosquito-control-business-peak-season',
  'reduce-mosquito-control-cancellations',
  'track-mosquito-control-revenue',
  'mosquito-control-software-vs-pest-control-tools',
  'handle-overdue-mosquito-control-treatments',
  'mosquito-control-program-pricing',
  'build-mosquito-control-business-year-over-year',
  // Spray Business
  'run-spray-business-without-office-manager',
  'dispatch-spray-technicians-fast',
  'what-software-does-a-spray-business-need',
  'build-spray-routes-circle-map',
  'manage-multiple-service-types-spray-business',
  'track-chemical-applications-compliance-spray-business',
  'automated-customer-alerts-spray-service',
  'grow-spray-business-startup-to-500-customers',
  'handle-recurring-spray-programs-auto-scheduling',
  'manage-spray-technicians-field',
  'price-spray-services-square-foot-linear-foot',
  'card-on-file-payments-spray-programs',
  'spray-service-estimates-to-scheduled-jobs',
  'track-spray-business-revenue',
  'spray-business-scaling-mistakes',
  'reduce-spray-business-cancellations-sms',
  'spray-business-software-roi',
  'manage-spray-business-multiple-crews',
  'what-to-look-for-spray-business-software',
  'build-spray-business-runs-without-you',
  // Pest Control Software
  'why-pest-control-software-recurring-treatments',
  'pest-control-software-track-remaining-treatments',
  'pest-control-compliance-report-state-inspection',
  'pest-control-software-re-service-calls',
  'manage-annual-pest-control-contracts-software',
  'pest-control-software-estimate-to-renewal',
  'know-pest-control-customers-up-for-renewal',
  'pest-control-interior-exterior-treatment-logs',
  'pest-control-state-inspector-chemical-logs',
  'set-up-quarterly-bimonthly-monthly-pest-control-software',
  'pest-control-software-re-entry-interval-compliance',
  'pest-control-estimates-convert-recurring-programs',
  'pest-control-software-estimate-to-first-service',
  'manage-multiple-pest-control-technicians-software',
  'pest-control-software-payment-collection-recurring',
  'grow-pest-control-business-without-office-manager',
  'pest-control-software-vs-generic-field-service',
  'pest-control-software-commercial-vs-residential',
  'pest-control-business-200-to-500-accounts-software',
  'evaluate-pest-control-software',
  // Lawn Care Software
  'what-is-lawn-care-software',
  'lawn-care-software-replaces-spreadsheets',
  'lawn-care-software-waiting-list',
  'best-lawn-care-software-vs-generic',
  'lawn-care-software-chemical-compliance',
  'set-up-lawn-care-customer-software',
  'lawn-care-software-route-revenue',
  'lawn-care-software-client-notes-property-details',
  'lawn-care-software-reduce-scheduling-time',
  'track-chemical-applications-lawn-care-software',
  'lawn-care-software-customer-notifications',
  'grow-lawn-care-business-50-to-300',
  'lawn-care-software-features',
  'lawn-care-software-multiple-service-types',
  'dispatch-lawn-care-crews-software',
  'know-route-revenue-before-dispatch',
  'lawn-care-software-pricing',
  'lawn-care-software-roi-90-days',
  'evaluate-lawn-care-software',
  'transition-lawn-care-business-spreadsheets-to-software',
  // Mosquito Spray Software
  'run-mosquito-spray-business-single-platform',
  'mosquito-spray-sq-ft-vs-linear-ft-pricing',
  'mosquito-spray-software-seasonal-startup-shutdown',
  'build-mosquito-spray-route-circle-map',
  'price-mosquito-barrier-spray-programs',
  'add-mosquito-spraying-lawn-care-pest-control-business',
  'mosquito-spray-business-equipment-products',
  'mosquito-spray-software-barrier-spray-epa-compliance',
  'scale-mosquito-spray-business-peak-season',
  'mosquito-barrier-spray-software-vs-generic',
  'manage-21-day-interval-mosquito-programs',
  'automated-sms-mosquito-spray-customer-retention',
  'mosquito-spray-customer-re-entry-communication',
  'know-overdue-mosquito-spray-customers-peak-season',
  'dispatch-mosquito-spray-technicians',
  'mosquito-spray-business-profitability-per-route-day',
  'close-mosquito-spray-season-last-treatments',
  'mosquito-spray-software-linear-foot-measurements',
  'grow-mosquito-spray-business-primary-revenue',
  'mosquito-spray-business-vs-other-pest-control',
];

export default function sitemap(): MetadataRoute.Sitemap {
  const entries: MetadataRoute.Sitemap = [
    {
      url: BASE,
      lastModified: new Date('2026-06-21'),
      changeFrequency: 'weekly',
      priority: 1.0,
    },
    {
      url: `${BASE}/blogs`,
      lastModified: new Date('2026-06-21'),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE}/features`,
      lastModified: new Date('2026-06-21'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${BASE}/pricing`,
      lastModified: new Date('2026-06-21'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
  ];

  for (const path of hubPages) {
    entries.push({
      url: `${BASE}${path}`,
      lastModified: new Date('2026-06-21'),
      changeFrequency: 'monthly',
      priority: 0.9,
    });
  }

  for (const path of vsPages) {
    entries.push({
      url: `${BASE}${path}`,
      lastModified: new Date('2026-06-21'),
      changeFrequency: 'monthly',
      priority: 0.8,
    });
  }

  for (const slug of blogSlugs) {
    entries.push({
      url: `${BASE}/blogs/${slug}`,
      lastModified: new Date('2026-06-21'),
      changeFrequency: 'monthly',
      priority: 0.7,
    });
  }

  return entries;
}
